### ISSUE TITLE
Rotate through selected coins instead of showing all in static

### ISSUE THREAD

**Issue by scottrepreneur** [justyntemme/cointick#2]
When there are multiple coins selected, rotate which coin is shown in the menu. If more than a few are selected this gets to be very congested in the menu. A nice slow, 5 seconds or so, rotation would be great to go through each and not overwhelm the menu bar.

**Comment by justyntemme** [comment]
When i have free time this weekend i will implement. Didn't even know anyone used this.

**Comment by justyntemme** [comment]
https://github.com/justyntemme/cointick/commit/fcab1a3d61da61b167ca26d377e4e81b94fa2be6

use -rotate=true to enable
