### ISSUE TITLE
Feature Request: More Currencies

### ISSUE THREAD

**Issue by blunket** [justyntemme/cointick#8]
Support more than USD? Might be a big feature request... Just a thought though

e.g.:
`--money="eur"`
> Ask: 6990,18   Bid: 6985,20

or with `--money-fmt`  (as in #7 )
> Ask: 6.990,18 €  Bid: 6.985,20 €

**Comment by justyntemme** [comment]
This is a feature request for the goCoinFetch package. Cointick just displays the info and would require deleting the "USD" at the beginning of the print statement.
